apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Keycloak.ServiceName }}
  labels:
    app: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.Keycloak.ServiceName }}
  replicas: {{ .Values.Keycloak.Replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.Keycloak.ServiceName }}
      annotations:
        kubectl.kubernetes.io/default-container: "keycloak"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/auth/metrics"
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.NodeRestrictions.Key }}"
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "{{ .Values.NodeRestrictions.Key }}"
                operator: In
                values:
                - {{ .Values.NodeRestrictions.Value }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          args:
          - /bin/sh
          - -c
          - | 
            set -x;
            while ! psql -U {{ .Values.Citus.AdminUser }} -h postgres -c 'select 1'; do
              echo "Waiting for DB to be available"
              sleep 10
            done
            echo "Database is available"
      containers:
        - name: keycloak
          image: {{ include "lokahi.image" (dict "Values" .Values "thisService" .Values.Keycloak) | quote }}
          imagePullPolicy: "{{ .Values.Keycloak.ImagePullPolicy }}"
          resources:
            limits:
              cpu: "{{ .Values.Keycloak.Resources.Limits.Cpu }}"
              memory: "{{ .Values.Keycloak.Resources.Limits.Memory }}"
            requests:
              cpu: "{{ .Values.Keycloak.Resources.Requests.Cpu }}"
              memory: "{{ .Values.Keycloak.Resources.Requests.Memory }}"
          args:
            - --import-realm
            {{- if .Values.OpenNMS.global.enableJsonLogging }}
            - --log-console-output=json
            {{- end }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/keycloak/agent/opentelemetry-javaagent.jar"
            - name: KC_CACHE_STACK
              value: kubernetes
            - name: KC_CACHE
              value: ispn
            - name: KC_HOSTNAME_URL # Required in prod-mod to terminate TLS at Ingress
            {{- if .Values.Keycloak.HostnamePort }}
              value: "{{ .Values.Protocol }}://{{ .Values.Host }}:{{ .Values.Keycloak.HostnamePort }}{{ .Values.Keycloak.Path }}"
            {{- else }}
              value: "{{ .Values.Protocol }}://{{ .Values.Host }}{{ .Values.Keycloak.Path }}"
            {{- end }}
            {{- if .Values.Keycloak.HostnameAdminUrl }}
            - name: KC_HOSTNAME_ADMIN_URL
              value: "{{ .Values.Keycloak.HostnameAdminUrl }}"
            {{- end }}
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Values.Keycloak.DbHost }}:5432/{{ .Values.Keycloak.DbName }}?currentSchema={{ .Values.Keycloak.DbSchemaName }}"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: keycloakUser
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: keycloakPwd
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_RELATIVE_PATH
              value: "{{ .Values.Keycloak.Path }}"
            - name: KC_PROXY
              value: edge # Required in prod-mod to terminate TLS at Ingress
            - name: jgroups.dns.query
              value: "{{ .Values.Keycloak.ServiceName }}.{{ .Release.Namespace }}"
            {{- if and .Values.TLS.Enabled .Values.Keycloak.TlsSecretName }}
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/mnt/certificates/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/mnt/certificates/tls.key"
            {{- end }}
            {{- if .Values.OpenShift }}
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            {{- end }}
            {{- range $Variable, $Value := .Values.Keycloak.Environment }}
            - name: {{ $Variable | quote }}
              value: {{ $Value | quote }}
            {{- end }}
            {{- if .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint | toYaml }}
            {{- else }}
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            {{- end }}
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            {{- if .Values.OpenNMS.global.openTelemetry.env }}
              {{- range $key, $val := .Values.OpenNMS.global.openTelemetry.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
              {{- end }}
            {{- end }}
            # Do not put any env variables below this. The lokahi.development.env include should be last
            # in the 'env' section so variables can be overridden with Helm chart values when needed.
            {{- include "lokahi.deployment.env" (dict "Values" .Values "thisService" .Values.Keycloak) | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.Keycloak.Port }}
            - name: https
              containerPort: {{ .Values.Keycloak.HttpsPort }}
          volumeMounts:
            {{- if and .Values.TLS.Enabled .Values.Keycloak.TlsSecretName }}
            - mountPath: /mnt/certificates
              name: keycloak-tls-certificates
            {{- end }}
            - mountPath: /opt/keycloak/data/import
              name: realm-config
          #startupProbe:
          #  httpGet:
          #    {{- if and .Values.TLS.Enabled .Values.Keycloak.TlsSecretName }}
          #    scheme: HTTPS
          #    port: https
          #    {{- else }}
          #    scheme: HTTP
          #    port: http
          #    {{- end }}
          #    path: {{ .Values.Keycloak.Path }}/health/live
          #  failureThreshold: 150
          #  periodSeconds: 5
          livenessProbe:
            httpGet:
              {{- if and .Values.TLS.Enabled .Values.Keycloak.TlsSecretName }}
              scheme: HTTPS
              port: https
              {{- else }}
              scheme: HTTP
              port: http
              {{- end }}
              path: {{ .Values.Keycloak.Path }}/health/live
            failureThreshold: 150
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              {{- if and .Values.TLS.Enabled .Values.Keycloak.TlsSecretName }}
              scheme: HTTPS
              port: https
              {{- else }}
              scheme: HTTP
              port: http
              {{- end }}
              path: {{ .Values.Keycloak.Path }}/health/ready
            failureThreshold: 250
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
      {{- if .Values.Keycloak.PrivateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}
      volumes:
        {{- if and .Values.TLS.Enabled .Values.Keycloak.TlsSecretName }}
        - name: keycloak-tls-certificates
          secret:
            defaultMode: 420
            optional: false
            secretName: {{ .Values.Keycloak.TlsSecretName }}
        {{- end }}
        - name: realm-config
          configMap:
            name: {{ .Values.Keycloak.ConfigmapName }}
