{{- if .Values.keycloak.DynamicRealmConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-configmap
  namespace: {{ .Release.Namespace }}
data:
  onms-realm.json: |
{{ tpl (.Files.Get "onms-realm.json") . | indent 4 }}
{{- end }}
