server:
  # Tried using default 8080, get 404 error.
  # Also, tried adding this setting to grpc section below, also did not work.
  port: 9090
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER

spring:
  jackson:
    default-property-inclusion: non_null

keycloak:
  url: http://onms-keycloak:8080/auth
  realm: opennms
  signatureAlgorithm: RS256

lokahi:
  bff:
    max-field-occurrence: 5
    max-query-depth: 20
    introspection-enabled: false

graphql:
  spqr:
    gui:
      enabled: true
    base-packages:
      - org.opennms.horizon.server.model
    max-complexity: 100

logging:
  file.path: /var/log/restServer
tsdb.url: http://localhost:59090/api/v1

grpc:
  url:
    inventory: localhost:29065
    events: localhost:30065
    notification: localhost:15065
    alerts: opennms-alert:6565
  server:
    deadline: 60000

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

