nodeRestrictions: # will be applied to every pod in the instance
  enabled: false
  key: kubernetes.azure.com/scalesetpriority
  value: spot

prometheus:
  enabled: true
  path: /prometheus
  serviceName: prometheus
  port: 9090
  image: prom/prometheus:v2.39.1
  replicas: 1
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 100Mi
