{{- if eq (include "onOpenShift" .) "false" }}
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.serviceName }}-sa
  labels:
    app: {{ .Values.prometheus.serviceName }}
{{- end }}
{{- end }}