apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.MinionGateway.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.MinionGateway.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
    - port: 8990
      protocol: TCP
      name: grpc
    - port: {{ .Values.OpenNMS.MinionGateway.InternalGrpcPort }}
      protocol: TCP
      name: internal-grpc
    - port: 10800
      protocol: TCP
      name: ig-client
    - port: 47500
      protocol: TCP
      name: ig-discovery
    - port: 47100
      protocol: TCP
      name: ig-spi
  selector:
    app: {{ .Values.OpenNMS.MinionGateway.serviceName }}
