{{- if .Values.Citus.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: citus-worker
spec:
  selector:
    app: citus-worker
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
{{- end }}
