{{- if .Values.citus.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.citus.serviceName }}
stringData:
  password: UEBzc3dvcmQxMjM=

  adminUser: "postgres"
  adminPwd: ".Values.citus.adminPassword"
  opennmsUser: "opennms"
  opennmsPwd: ".Values.citus.openNMSPassword"
  keycloakUser: "keycloak"
  keycloakPwd: ".Values.citus.keycloakPassword"
  inventoryUser: "inventory"
  inventoryPwd: ".Values.citus.inventoryPassword"
  alertUser: "alert"
  alertPwd: ".Values.citus.alertPassword"
  notificationUser: "notification"
  notificationPwd: ".Values.citus.notificationPassword"
  grafanaUser: "grafana"
  grafanaPwd: ".Values.citus.grafanaPassword"
  eventsUser: "events"
  eventsPwd: ".Values.citus.eventsPassword"
  dataChoicesUsr: "datachoices"
  dataChoicesPwd: ".Values.citus.dataChoicesPassword"
  minionGatewayUsr: "minion_gateway"
  minionGatewayPwd: ".Values.citus.minionGatewayPassword"
type: Opaque
{{- end }}

