{{- if .Values.Citus.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: citus
spec:
  selector:
    app: citus
  clusterIP: None
  ports:
  - port: 5432
    name: postgres
{{- end }}
