{{- if .Values.Citus.Enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: citus-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: citus-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: citus-cert
  commonName: citus.default
  dnsNames:
  - '*.{{ .Values.Citus.serviceName }}.default.svc.cluster.local'
  issuerRef:
    name: citus-issuer

{{- end }}
