{{- if eq (include "onOpenShift" .) "true" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opennms-grafana-route
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.hostname }}.apps-crc.testing
  path: {{ .Values.Grafana.Path }}  
  to:
    kind: Service
    name: {{ .Values.Grafana.ServiceName }}
{{- end }}