{{- if eq (include "onOpenShift" .) "true" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opennms-minion-grpc-route
  namespace: {{ .Release.Namespace }}
spec:
  host: "minion.{{ .Values.hostname }}.apps-crc.testing"
  port:
    targetPort: {{ .Values.OpenNMS.minionGateway.GrpcPort }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: {{ .Values.OpenNMS.minionGateway.serviceName }}
{{- end }}