{{- if eq (include "onOpenShift" .) "true" }}
piVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opennms-keycloak-route
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.hostname }}.apps-crc.testing
  path: {{ .Values.Keycloak.path }}  
  to:
    kind: Service
    name: {{ .Values.Keycloak.serviceName }}
{{- end }}