apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.openNMS.inventory.serviceName }}
  labels:
    app: {{ .Values.openNMS.inventory.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
    - port: 6565
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.openNMS.inventory.serviceName }}
