spring:
  application:
    name: horizon-stream-notifications

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/notification
    username: notification
    password: passw0rd

  kafka:
    consumer:
      group-id: org.opennms.horizon.notifications
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.opennms.horizon.shared.dto.event
        spring.json.value.default.type: org.opennms.horizon.shared.dto.event.AlarmDTO

  liquibase:
    change-log: db/changelog/changelog.xml

horizon:
  kafka:
    alarms:
      topic: org.opennms.horizon.notifications.alarms
      concurrency: 1

  pagerduty:
    client: OpenNMS
    clientURL: http://opennms.com

  keycloak:
    realm: opennms
    use-static-pubkey: false
    keycloakRequireSsl: false
    static-pubkey-path: etc/keycloak-pubkey.pem
    base-url: http://keycloak:8080
    admin-realm: master
    admin-username: keycloak-admin
    admin-password: admin
#      <cm:property name="keycloak.base-url" value="$[env:KEYCLOAK_BASE_URL]"/>
#      <cm:property name="keycloak.admin-username" value="$[env:KEYCLOAK_ADMIN_USERNAME]" />
#      <cm:property name="keycloak.admin-password" value="$[env:KEYCLOAK_ADMIN_PASSWORD]" />
