{{- if .Values.ingress.enabled }}
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-{{ .Release.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/part-of: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/version: 1.3.0
  name: ingress-nginx-controller
  namespace: {{ .Release.Namespace }}
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: '' #Leave it empty to force LoadBalancer in OpenShift
  ports:
    - appProtocol: http
      name: http
      port: {{ .Values.ingress.httpPort }}
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      port: {{ .Values.ingress.httpsPort }}
      protocol: TCP
      targetPort: https
  sessionAffinity: None
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: controller-{{ .Release.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Release.Namespace }}
{{- end }}
